approvedGitRepositories:
  - "**"

catalog:
  zod: ^4.3.6

changesetIgnorePatterns:
  - "**/*.test.{js,ts,jsx,tsx}"
  - "**/__fixtures__/**/*"
  - package.json
  - "**/tsconfig.json"
  - "**/README.md"
  - "**/.gitignore"
  - "**/.yarnrc.yml"
  - .devcontainer/*
  - .vscode/*
  - .husky/*
  - .yarn/*
  - config/**/*

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 4320

preferDeferredVersions: true
