{ pkgs, ... }:

{
  packages = [
    pkgs.ffmpeg
    # Order is important here — we need sqlite-interactive's
    # sqlite3 executable to come first in the path,
    # but we also want the development headers, which are
    # in the sqlite package.
    pkgs.sqlite-interactive
    pkgs.sqlite
    pkgs.git-lfs
    pkgs.vtsls
    pkgs.google-cloud-sdk
    # note: readium cli will be installed via task below
  ];

  languages.javascript = {
    enable = true;
    package = pkgs.nodejs_24;
    corepack.enable = true;
  };

  tasks."repo:init" = {
    description = "Do necessary work for setting up development";
    exec = ''
      yarn install
      git lfs pull

      # install readium cli for development using our reusable script
      ./web/install-readium-cli.sh 0.6.5

      touch .devenv-initialized'';
    status = "test -f .devenv-initialized";
    before = [
      "devenv:enterShell"
      "devenv:enterTest"
    ];
  };

  devcontainer.enable = true;
  devcontainer.settings._COMMENT1 = "This file is auto-generated by devenv.nix";
  devcontainer.settings._COMMENT2 = "It gets overwritten by devenv and the devcontainer.";
  devcontainer.settings.customizations.vscode.extensions = [
    # Default; needed to make devenv devcontainer work
    "mkhl.direnv"
    # Copied from .vscode/extensions.json
    "arcanis.vscode-zipfs"
    "dbaeumer.vscode-eslint"
    "esbenp.prettier-vscode"
    "ms-python.python"
    "ms-python.vscode-pylance"
    "ms-azuretools.vscode-docker"
    "ms-python.black-formatter"
    "bbenoist.nix"
    "gitlab.gitlab-workflow"
    "redhat.vscode-yaml"
  ];
  devcontainer.settings.updateContentCommand = ''
    direnv allow
    mkdir -p ~/.local/share/nix/
    echo -n '{"extra-substituters":{"https://devenv.cachix.org":true},"extra-trusted-public-keys":{"devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=":true}}' > ~/.local/share/nix/trusted-settings.json
    DIRENV_WARN_TIMEOUT=0 direnv exec ''${containerWorkspaceFolder} devenv test'';
  devcontainer.settings.containerEnv = {
    DEV_CONTAINER = "true";
  };

  enterTest = "yarn check";
}
