import assert from "node:assert"
import { describe, it } from "node:test"

import { type SentenceRange } from "../getSentenceRanges.ts"
import {
  interpolateSentenceRanges,
  slotKey,
} from "../interpolateSentenceRanges.ts"

// NOTE: This test suite was generated by an LLM.
// It has been reviewed by human software engineers, but it should not
// be taken as a standard or model test suite for this project.

// ─── helpers ────────────────────────────────────────────────────────────────

/** Build a SentenceRange with convenient defaults. */
function sr(
  chapterId: string,
  id: number,
  start: number,
  end: number,
  audiofile = "audio.mp3",
): SentenceRange {
  return { chapterId, id, start, end, audiofile }
}

/** Assert that start/end times are monotonically non-decreasing within each
 *  audiofile (sentences in the same file must not overlap). */

// ─── basic cases ────────────────────────────────────────────────────────────

void describe("no gaps", () => {
  void it("returns input unchanged when the chapter is complete", () => {
    const input = [
      sr("ch1", 0, 0, 5),
      sr("ch1", 1, 5, 10),
      sr("ch1", 2, 10, 15),
    ]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 3 },
      { "audio.mp3": 20 },
    )
    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 0, end: 5, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 1, start: 5, end: 10, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 2, start: 10, end: 15, audiofile: "audio.mp3" },
    ])
  })

  void it("handles multiple complete chapters with no gaps", () => {
    const input = [
      sr("ch1", 0, 0, 10),
      sr("ch1", 1, 10, 20),
      sr("ch2", 0, 20, 30),
      sr("ch2", 1, 30, 40),
    ]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 2, ch2: 2 },
      { "audio.mp3": 50 },
    )
    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 0, end: 10, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 1, start: 10, end: 20, audiofile: "audio.mp3" },
      { chapterId: "ch2", id: 0, start: 20, end: 30, audiofile: "audio.mp3" },
      { chapterId: "ch2", id: 1, start: 30, end: 40, audiofile: "audio.mp3" },
    ])
  })
})

void describe("empty input", () => {
  void it("returns an empty array", () => {
    const result = interpolateSentenceRanges([], {}, {})
    assert.deepStrictEqual(result, [])
  })
})

// ─── within-chapter gaps ────────────────────────────────────────────────────

void describe("within-chapter gap (same audiofile)", () => {
  void it("fills a gap of 2 sentences between two known sentences", () => {
    // Known: #0 ends at t=10, #3 starts at t=40
    // Missing: #1, #2 → should occupy [10, 40] evenly
    const input = [sr("ch1", 0, 0, 10), sr("ch1", 3, 40, 50)]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 4 },
      { "audio.mp3": 60 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 0, end: 10, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "audio.mp3", start: 10, end: 25 },
      { chapterId: "ch1", id: 2, audiofile: "audio.mp3", start: 25, end: 40 },
      { chapterId: "ch1", id: 3, start: 40, end: 50, audiofile: "audio.mp3" },
    ])
  })

  void it("fills a single missing sentence", () => {
    const input = [sr("ch1", 0, 0, 10), sr("ch1", 2, 20, 30)]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 3 },
      { "audio.mp3": 40 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 0, end: 10, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "audio.mp3", start: 10, end: 20 },
      { chapterId: "ch1", id: 2, start: 20, end: 30, audiofile: "audio.mp3" },
    ])
  })

  void it("fills multiple disjoint gaps within a chapter", () => {
    // Known: #0, #2, #4  →  missing #1, #3
    const input = [
      sr("ch1", 0, 0, 10),
      sr("ch1", 2, 20, 30),
      sr("ch1", 4, 40, 50),
    ]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 5 },
      { "audio.mp3": 60 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 0, end: 10, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "audio.mp3", start: 10, end: 20 },
      { chapterId: "ch1", id: 2, start: 20, end: 30, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 3, audiofile: "audio.mp3", start: 30, end: 40 },
      { chapterId: "ch1", id: 4, start: 40, end: 50, audiofile: "audio.mp3" },
    ])
  })
})

// ─── leading-gap cases ──────────────────────────────────────────────────────

void describe("leading gap (chapter starts at id > 0)", () => {
  void it("fills missing sentences before the first known sentence", () => {
    // First known is #2; need to interpolate #0 and #1 from t=0 to t=20
    const input = [sr("ch1", 2, 20, 30)]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 3 },
      { "audio.mp3": 40 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, audiofile: "audio.mp3", start: 0, end: 10 },
      { chapterId: "ch1", id: 1, audiofile: "audio.mp3", start: 10, end: 20 },
      { chapterId: "ch1", id: 2, start: 20, end: 30, audiofile: "audio.mp3" },
    ])
  })

  void it("fills a single missing leading sentence", () => {
    const input = [sr("ch1", 1, 15, 30)]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 2 },
      { "audio.mp3": 40 },
    )
    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, audiofile: "audio.mp3", start: 0, end: 15 },
      { chapterId: "ch1", id: 1, start: 15, end: 30, audiofile: "audio.mp3" },
    ])
  })
})

// ─── trailing-gap cases ─────────────────────────────────────────────────────

void describe("trailing gap (chapter ends before total count)", () => {
  void it("fills missing sentences after the last known sentence", () => {
    // Last known is #0 ending at t=10; chapter has 3 sentences; file runs to t=40
    const input = [sr("ch1", 0, 0, 10)]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 3 },
      { "audio.mp3": 40 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 0, end: 10, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "audio.mp3", start: 10, end: 25 },
      { chapterId: "ch1", id: 2, audiofile: "audio.mp3", start: 25, end: 40 },
    ])
  })

  void it("fills a single missing trailing sentence", () => {
    const input = [sr("ch1", 0, 0, 20)]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 2 },
      { "audio.mp3": 40 },
    )
    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 0, end: 20, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "audio.mp3", start: 20, end: 40 },
    ])
  })
})

// ─── chapter-boundary gaps ──────────────────────────────────────────────────

void describe("gap spanning a chapter boundary (same audiofile)", () => {
  void it("fills trailing gap of ch1 and leading gap of ch2", () => {
    // ch1: only sentence #0 known; needs #1, #2
    // ch2: only sentence #2 known; needs #0, #1
    // Both in the same file; ch1#0 ends at t=10, ch2#2 starts at t=50
    const input = [sr("ch1", 0, 0, 10), sr("ch2", 2, 50, 60)]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 3, ch2: 3 },
      { "audio.mp3": 70 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 0, end: 10, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "audio.mp3", start: 10, end: 20 },
      { chapterId: "ch1", id: 2, audiofile: "audio.mp3", start: 20, end: 30 },
      { chapterId: "ch2", id: 0, audiofile: "audio.mp3", start: 30, end: 40 },
      { chapterId: "ch2", id: 1, audiofile: "audio.mp3", start: 40, end: 50 },
      { chapterId: "ch2", id: 2, start: 50, end: 60, audiofile: "audio.mp3" },
    ])
  })

  void it("handles no trailing gap in ch1 but a leading gap in ch2", () => {
    const input = [
      sr("ch1", 0, 0, 10),
      sr("ch1", 1, 10, 20),
      sr("ch2", 2, 40, 50),
    ]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 2, ch2: 3 },
      { "audio.mp3": 60 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 0, end: 10, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 1, start: 10, end: 20, audiofile: "audio.mp3" },
      { chapterId: "ch2", id: 0, audiofile: "audio.mp3", start: 20, end: 30 },
      { chapterId: "ch2", id: 1, audiofile: "audio.mp3", start: 30, end: 40 },
      { chapterId: "ch2", id: 2, start: 40, end: 50, audiofile: "audio.mp3" },
    ])
  })

  void it("handles a trailing gap in ch1 but no leading gap in ch2", () => {
    const input = [sr("ch1", 0, 0, 10), sr("ch2", 0, 30, 40)]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 3, ch2: 1 },
      { "audio.mp3": 50 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 0, end: 10, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "audio.mp3", start: 10, end: 20 },
      { chapterId: "ch1", id: 2, audiofile: "audio.mp3", start: 20, end: 30 },
      { chapterId: "ch2", id: 0, start: 30, end: 40, audiofile: "audio.mp3" },
    ])
  })
})

// ─── cross-file gaps ────────────────────────────────────────────────────────

void describe("gap spanning an audiofile boundary", () => {
  void it("splits interpolated sentences proportionally across two files", () => {
    // file-a.mp3 runs 0–100s; known sentence ends at t=80 (20s remaining)
    // file-b.mp3 runs 0–100s; next known sentence starts at t=20 (20s available)
    // 4 missing sentences → should split 2 in file-a, 2 in file-b (equal proportion)
    const input = [
      sr("ch1", 0, 70, 80, "file-a.mp3"),
      sr("ch1", 5, 20, 30, "file-b.mp3"),
    ]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 6 },
      { "file-a.mp3": 100, "file-b.mp3": 100 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 70, end: 80, audiofile: "file-a.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "file-a.mp3", start: 80, end: 90 },
      { chapterId: "ch1", id: 2, audiofile: "file-a.mp3", start: 90, end: 100 },
      { chapterId: "ch1", id: 3, audiofile: "file-b.mp3", start: 0, end: 10 },
      { chapterId: "ch1", id: 4, audiofile: "file-b.mp3", start: 10, end: 20 },
      { chapterId: "ch1", id: 5, start: 20, end: 30, audiofile: "file-b.mp3" },
    ])
  })

  void it("assigns all sentences to the latter file when prior file has no remaining time", () => {
    // Sentence ends exactly at the end of file-a; all gap goes to file-b
    const input = [
      sr("ch1", 0, 90, 100, "file-a.mp3"),
      sr("ch1", 3, 30, 40, "file-b.mp3"),
    ]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 4 },
      { "file-a.mp3": 100, "file-b.mp3": 50 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 90, end: 100, audiofile: "file-a.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "file-b.mp3", start: 0, end: 15 },
      { chapterId: "ch1", id: 2, audiofile: "file-b.mp3", start: 15, end: 30 },
      { chapterId: "ch1", id: 3, start: 30, end: 40, audiofile: "file-b.mp3" },
    ])
  })

  void it("assigns all sentences to the prior file when the latter file starts at 0", () => {
    // Next known sentence starts at t=0 in file-b (no available time in file-b before it)
    const input = [
      sr("ch1", 0, 50, 60, "file-a.mp3"),
      sr("ch1", 3, 0, 10, "file-b.mp3"),
    ]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 4 },
      { "file-a.mp3": 100, "file-b.mp3": 50 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 50, end: 60, audiofile: "file-a.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "file-a.mp3", start: 60, end: 80 },
      { chapterId: "ch1", id: 2, audiofile: "file-a.mp3", start: 80, end: 100 },
      { chapterId: "ch1", id: 3, start: 0, end: 10, audiofile: "file-b.mp3" },
    ])
  })

  void it("handles a cross-file leading gap (first sentence is in a later file)", () => {
    // First known sentence is #2 in file-b; #0 and #1 must be in file-b as well
    const input = [sr("ch1", 2, 20, 30, "file-b.mp3")]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 3 },
      { "file-a.mp3": 100, "file-b.mp3": 50 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, audiofile: "file-b.mp3", start: 0, end: 10 },
      { chapterId: "ch1", id: 1, audiofile: "file-b.mp3", start: 10, end: 20 },
      { chapterId: "ch1", id: 2, start: 20, end: 30, audiofile: "file-b.mp3" },
    ])
  })

  void it("handles a cross-file trailing gap (last sentence is in an earlier file)", () => {
    // Last known sentence in ch1 is #0 in file-a; trailing sentences must be in file-a
    const input = [sr("ch1", 0, 10, 20, "file-a.mp3")]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 3 },
      { "file-a.mp3": 50, "file-b.mp3": 100 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 10, end: 20, audiofile: "file-a.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "file-a.mp3", start: 20, end: 35 },
      { chapterId: "ch1", id: 2, audiofile: "file-a.mp3", start: 35, end: 50 },
    ])
  })
})

// ─── ordering guarantees ────────────────────────────────────────────────────

void describe("output ordering", () => {
  void it("preserves overall playback order through multiple chapters", () => {
    const input = [
      sr("ch1", 0, 0, 5),
      sr("ch1", 2, 15, 20),
      sr("ch2", 0, 25, 30),
    ]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 3, ch2: 1 },
      { "audio.mp3": 40 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 0, end: 5, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "audio.mp3", start: 5, end: 15 },
      { chapterId: "ch1", id: 2, start: 15, end: 20, audiofile: "audio.mp3" },
      { chapterId: "ch2", id: 0, start: 25, end: 30, audiofile: "audio.mp3" },
    ])
  })

  void it("known sentences retain their original start/end/audiofile values", () => {
    const input = [sr("ch1", 0, 1.5, 3.7), sr("ch1", 2, 7.1, 9.9)]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 3 },
      { "audio.mp3": 15 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 1.5, end: 3.7, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "audio.mp3", start: 3.7, end: 7.1 },
      { chapterId: "ch1", id: 2, start: 7.1, end: 9.9, audiofile: "audio.mp3" },
    ])
  })
})

// ─── combined / realistic cases ─────────────────────────────────────────────

void describe("combined scenarios", () => {
  void it("handles both a leading and a trailing gap in the same chapter", () => {
    // Only sentence #2 is known in a 5-sentence chapter
    const input = [sr("ch1", 2, 40, 60)]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 5 },
      { "audio.mp3": 100 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, audiofile: "audio.mp3", start: 0, end: 20 },
      { chapterId: "ch1", id: 1, audiofile: "audio.mp3", start: 20, end: 40 },
      { chapterId: "ch1", id: 2, start: 40, end: 60, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 3, audiofile: "audio.mp3", start: 60, end: 80 },
      { chapterId: "ch1", id: 4, audiofile: "audio.mp3", start: 80, end: 100 },
    ])
  })

  void it("handles three chapters with various gap types", () => {
    // ch1: has #0 and #2 (3 total) – gap between them
    // ch2: has #1 only (3 total) – leading + trailing gap
    // ch3: has #0 (2 total) – trailing gap
    const input = [
      sr("ch1", 0, 0, 10),
      sr("ch1", 2, 20, 30),
      sr("ch2", 1, 40, 50),
      sr("ch3", 0, 70, 80),
    ]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 3, ch2: 3, ch3: 2 },
      { "audio.mp3": 100 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 0, end: 10, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "audio.mp3", start: 10, end: 20 },
      { chapterId: "ch1", id: 2, start: 20, end: 30, audiofile: "audio.mp3" },
      { chapterId: "ch2", id: 0, audiofile: "audio.mp3", start: 30, end: 40 },
      { chapterId: "ch2", id: 1, start: 40, end: 50, audiofile: "audio.mp3" },
      { chapterId: "ch2", id: 2, audiofile: "audio.mp3", start: 50, end: 70 },
      { chapterId: "ch3", id: 0, start: 70, end: 80, audiofile: "audio.mp3" },
      { chapterId: "ch3", id: 1, audiofile: "audio.mp3", start: 80, end: 100 },
    ])
  })

  void it("handles three chapters with separate audio files", () => {
    // ch1: has #0 and #2 (3 total) – gap between them
    // ch2: has #1 only (3 total) – leading + trailing gap
    // ch3: has #0 (2 total) – trailing gap
    const input = [
      sr("ch1", 0, 0, 10, "1.mp3"),
      sr("ch1", 2, 20, 30, "1.mp3"),
      sr("ch2", 1, 40, 50, "2.mp3"),
      sr("ch3", 0, 0, 80, "3.mp3"),
    ]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 3, ch2: 3, ch3: 2 },
      { "1.mp3": 30, "2.mp3": 60, "3.mp3": 100 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 0, end: 10, audiofile: "1.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "1.mp3", start: 10, end: 20 },
      { chapterId: "ch1", id: 2, start: 20, end: 30, audiofile: "1.mp3" },
      { chapterId: "ch2", id: 0, audiofile: "2.mp3", start: 0, end: 40 },
      { chapterId: "ch2", id: 1, start: 40, end: 50, audiofile: "2.mp3" },
      { chapterId: "ch2", id: 2, audiofile: "2.mp3", start: 50, end: 60 },
      { chapterId: "ch3", id: 0, start: 0, end: 80, audiofile: "3.mp3" },
      { chapterId: "ch3", id: 1, audiofile: "3.mp3", start: 80, end: 100 },
    ])
  })
})

// ─── sentence-length weighting ──────────────────────────────────────────────

void describe("sentence-length weighting", () => {
  void it("falls back to even division when no lengths are provided", () => {
    const input = [sr("ch1", 0, 0, 10), sr("ch1", 3, 40, 50)]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 4 },
      { "audio.mp3": 60 },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 0, end: 10, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "audio.mp3", start: 10, end: 25 },
      { chapterId: "ch1", id: 2, audiofile: "audio.mp3", start: 25, end: 40 },
      { chapterId: "ch1", id: 3, start: 40, end: 50, audiofile: "audio.mp3" },
    ])
  })

  void it("splits a gap proportionally to sentence length instead of evenly", () => {
    // Known: #0 ends at t=10, #3 starts at t=40 → 30s to split across #1, #2.
    // #1 is a short sentence (10 chars), #2 is three times as long (30 chars),
    // so #2 should get three times as much of the 30s as #1 (7.5s vs 22.5s),
    // not an even 15s/15s split.
    const input = [sr("ch1", 0, 0, 10), sr("ch1", 3, 40, 50)]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 4 },
      { "audio.mp3": 60 },
      {
        [slotKey({ chapterId: "ch1", id: 1 })]: 10,
        [slotKey({ chapterId: "ch1", id: 2 })]: 30,
      },
    )

    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 0, end: 10, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "audio.mp3", start: 10, end: 17.5 },
      { chapterId: "ch1", id: 2, audiofile: "audio.mp3", start: 17.5, end: 40 },
      { chapterId: "ch1", id: 3, start: 40, end: 50, audiofile: "audio.mp3" },
    ])
  })

  void it("treats a missing or non-positive length as weight 1", () => {
    const input = [sr("ch1", 0, 0, 10), sr("ch1", 3, 40, 50)]
    const result = interpolateSentenceRanges(
      input,
      { ch1: 4 },
      { "audio.mp3": 60 },
      {
        [slotKey({ chapterId: "ch1", id: 1 })]: 0,
        [slotKey({ chapterId: "ch1", id: 2 })]: -5,
      },
    )

    // Both weights fall back to 1, so this should match the even-division case.
    assert.deepStrictEqual(result, [
      { chapterId: "ch1", id: 0, start: 0, end: 10, audiofile: "audio.mp3" },
      { chapterId: "ch1", id: 1, audiofile: "audio.mp3", start: 10, end: 25 },
      { chapterId: "ch1", id: 2, audiofile: "audio.mp3", start: 25, end: 40 },
      { chapterId: "ch1", id: 3, start: 40, end: 50, audiofile: "audio.mp3" },
    ])
  })
})
