/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely"

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export interface Account {
  accessToken: string | null
  createdAt: Generated<string>
  expiresAt: number | null
  id: Generated<import("@/uuid").UUID>
  idToken: string | null
  provider: string
  providerAccountId: string
  refreshToken: string | null
  scope: string | null
  sessionState: string | null
  tokenType: string | null
  type: string
  updatedAt: Generated<string>
  userId: string
}

export interface Audiobook {
  bookUuid: import("@/uuid").UUID
  createdAt: Generated<string>
  duration: number | null
  filepath: string
  fileSize: number | null
  fingerprint: string | null
  manifest: ColumnType<Record<string, unknown>, string, string> | null
  missing: Generated<boolean>
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface Book {
  alignedAt: string | null
  alignedByStorytellerVersion: string | null
  alignedWith: string | null
  assetDir: Generated<string>
  createdAt: Generated<string>
  description: string | null
  duration: number | null
  id: number | null
  language: Generated<string | null>
  pageCount: number | null
  publicationDate: string | null
  rating: number | null
  subtitle: string | null
  title: string
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface BookToCollection {
  bookUuid: import("@/uuid").UUID
  collectionUuid: import("@/uuid").UUID
  createdAt: Generated<string>
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface BookToCreator {
  bookUuid: import("@/uuid").UUID
  createdAt: Generated<string>
  creatorUuid: import("@/uuid").UUID
  role: import("@/components/books/edit/marcRelators").Role | null
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface BookToSeries {
  bookUuid: import("@/uuid").UUID
  createdAt: Generated<string>
  featured: Generated<boolean>
  position: number | null
  seriesUuid: import("@/uuid").UUID
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface BookToStatus {
  bookUuid: import("@/uuid").UUID
  createdAt: Generated<string>
  statusUuid: import("@/uuid").UUID
  updatedAt: Generated<string>
  userId: import("@/uuid").UUID
  uuid: Generated<import("@/uuid").UUID>
}

export interface BookToTag {
  bookUuid: import("@/uuid").UUID
  createdAt: Generated<string>
  tagUuid: import("@/uuid").UUID
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface Changelog {
  component: string
  createdAt: Generated<string>
  description: string | null
  releasedAt: string
  tagName: string
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
  version: string
}

export interface Collection {
  createdAt: Generated<string>
  description: string | null
  name: string
  public: Generated<boolean>
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface CollectionToUser {
  collectionUuid: import("@/uuid").UUID
  createdAt: Generated<string>
  updatedAt: Generated<string>
  userId: import("@/uuid").UUID
  uuid: Generated<import("@/uuid").UUID>
}

export interface Creator {
  createdAt: Generated<string>
  fileAs: string
  id: number | null
  name: string
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface DeviceAuthorization {
  approvedByUserId: import("@/uuid").UUID | null
  createdAt: Generated<string>
  deviceCode: string
  expiresAt: Date
  id: Generated<import("@/uuid").UUID>
  intervalSeconds: Generated<number>
  lastPolledAt: Date | null
  status: Generated<string>
  updatedAt: Generated<string>
  userCode: string
}

export interface Ebook {
  bookUuid: import("@/uuid").UUID
  createdAt: Generated<string>
  filepath: string
  fileSize: number | null
  fingerprint: string | null
  isEpub2: Generated<boolean>
  manifest: Record<string, unknown> | null
  missing: Generated<boolean>
  pageCount: number | null
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface ExternalData {
  createdAt: Generated<string>
  externalSourceUuid: import("@/uuid").UUID
  fetchedAt: Generated<string>
  identifierUuid: import("@/uuid").UUID
  rating: number
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface ExternalSource {
  color: string | null
  createdAt: Generated<string>
  kind: import("@/database/externalSources").ExternalSourceKind | null
  logo: string | null
  name: string
  ratingIcon: string | null
  ratingMax: number | null
  ratingMin: number | null
  updatedAt: Generated<string>
  url: string | null
  uuid: Generated<import("@/uuid").UUID>
}

export interface Identifier {
  audiobookUuid: import("@/uuid").UUID | null
  bookUuid: import("@/uuid").UUID
  createdAt: Generated<string>
  ebookUuid: import("@/uuid").UUID | null
  identifierTypeUuid: import("@/uuid").UUID
  readaloudUuid: import("@/uuid").UUID | null
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
  value: string
}

export interface IdentifierType {
  createdAt: Generated<string>
  externalSourceUuid: import("@/uuid").UUID | null
  kind: import("@/database/identifiers").IdentifierKind | null
  name: string
  updatedAt: Generated<string>
  urlTemplate: string | null
  uuid: Generated<import("@/uuid").UUID>
}

export interface ImportRule {
  bookUuid: import("@/uuid").UUID | null
  createdAt: Generated<string>
  epub2ImportStrategy:
    | import("@/database/settingsTypes").Epub2ImportStrategy
    | null
  importMode: import("@/database/settingsTypes").ImportMode | null
  kind: "watch" | "ignore"
  path: string
  source: Generated<
    "user" | "import-relocate" | "import-backup" | "prevent-reimport"
  >
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface ImportRuleToCollection {
  collectionUuid: import("@/uuid").UUID
  importRuleUuid: import("@/uuid").UUID
}

export interface Migration {
  createdAt: Generated<string>
  hash: string
  id: Generated<number>
  name: string
  updatedAt: Generated<string>
}

export interface Position {
  bookUuid: import("@/uuid").UUID
  createdAt: Generated<string>
  locator: import("kysely").ColumnType<
    import("@/database/positions").ReadiumLocator,
    string,
    string
  >
  timestamp: number
  updatedAt: Generated<string>
  userId: import("@/uuid").UUID
  uuid: Generated<import("@/uuid").UUID>
}

export interface Readaloud {
  bookUuid: import("@/uuid").UUID
  createdAt: Generated<string>
  currentStage: "SPLIT_TRACKS" | "TRANSCRIBE_CHAPTERS" | "SYNC_CHAPTERS"
  duration: number | null
  filepath: string | null
  fileSize: number | null
  fingerprint: string | null
  isEpub2: Generated<boolean>
  manifest: ColumnType<Record<string, unknown>, string, string> | null
  missing: Generated<boolean>
  pageCount: number | null
  queuePosition: number | null
  restartPending: import("@/work/distributor").RestartMode | null
  stageProgress: Generated<number>
  status: Generated<
    "CREATED" | "QUEUED" | "PROCESSING" | "STOPPED" | "ERROR" | "ALIGNED"
  >
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface Series {
  createdAt: Generated<string>
  description: string | null
  name: string
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface Session {
  createdAt: Generated<string>
  expires: Date
  id: Generated<import("@/uuid").UUID>
  sessionToken: string
  updatedAt: Generated<string>
  userId: import("@/uuid").UUID
}

export interface Settings {
  createdAt: Generated<string>
  id: number | null
  name: keyof import("@/database/settingsTypes").Settings
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
  value: string
}

export interface Status {
  createdAt: Generated<string>
  isDefault: Generated<boolean>
  name: string
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface Tag {
  createdAt: Generated<string>
  name: string
  updatedAt: Generated<string>
  uuid: Generated<import("@/uuid").UUID>
}

export interface TokenRevokation {
  createdAt: Generated<string>
  token: string
  updatedAt: Generated<string>
}

export interface User {
  createdAt: Generated<string>
  email: string
  emailVerified: Date | null
  hashedPassword: string | null
  id: Generated<import("@/uuid").UUID>
  inviteAccepted: Date | null
  inviteKey: string | null
  name: string | null
  updatedAt: Generated<string>
  username: string | null
  userPermissionUuid: import("@/uuid").UUID
}

export interface UserBookRating {
  bookUuid: import("@/uuid").UUID
  createdAt: Generated<string>
  rating: number | null
  review: string | null
  updatedAt: Generated<string>
  userId: import("@/uuid").UUID
  uuid: Generated<import("@/uuid").UUID>
}

export interface UserPermission {
  bookCreate: Generated<boolean>
  bookDelete: Generated<boolean>
  bookDownload: Generated<boolean>
  bookList: Generated<boolean>
  bookProcess: Generated<boolean>
  bookRead: Generated<boolean>
  bookUpdate: Generated<boolean>
  collectionCreate: Generated<boolean>
  createdAt: Generated<string>
  id: number | null
  inviteDelete: Generated<boolean>
  inviteList: Generated<boolean>
  settingsUpdate: Generated<boolean>
  updatedAt: Generated<string>
  userCreate: Generated<boolean>
  userDelete: Generated<boolean>
  userList: Generated<boolean>
  userPasswordReset: Generated<boolean>
  userRead: Generated<boolean>
  userUpdate: Generated<boolean>
  uuid: Generated<import("@/uuid").UUID>
}

export interface UserSettings {
  createdAt: Generated<string>
  name: string
  updatedAt: Generated<string>
  userId: import("@/uuid").UUID
  uuid: Generated<import("@/uuid").UUID>
  value: string | null
}

export interface VerificationToken {
  createdAt: Generated<string>
  expires: Date
  identifier: string
  token: string
  updatedAt: Generated<string>
}

export interface DB {
  account: Account
  audiobook: Audiobook
  book: Book
  bookToCollection: BookToCollection
  bookToCreator: BookToCreator
  bookToSeries: BookToSeries
  bookToStatus: BookToStatus
  bookToTag: BookToTag
  changelog: Changelog
  collection: Collection
  collectionToUser: CollectionToUser
  creator: Creator
  deviceAuthorization: DeviceAuthorization
  ebook: Ebook
  externalData: ExternalData
  externalSource: ExternalSource
  identifier: Identifier
  identifierType: IdentifierType
  importRule: ImportRule
  importRuleToCollection: ImportRuleToCollection
  migration: Migration
  position: Position
  readaloud: Readaloud
  series: Series
  session: Session
  settings: Settings
  status: Status
  tag: Tag
  tokenRevokation: TokenRevokation
  user: User
  userBookRating: UserBookRating
  userPermission: UserPermission
  userSettings: UserSettings
  verificationToken: VerificationToken
}
