// GENERATED by schemas/sync.ts. do not edit.
/* eslint-disable */
import type { AnySchemaObject } from "ajv"

import schema0 from "./vendor/drafts.opds.io/schema/authentication.schema.json" with { type: "json" }
import schema1 from "./vendor/drafts.opds.io/schema/progression.schema.json" with { type: "json" }
import schema2 from "./vendor/readium.org/webpub-manifest/schema/a11y.schema.json" with { type: "json" }
import schema3 from "./vendor/readium.org/webpub-manifest/schema/altIdentifier.schema.json" with { type: "json" }
import schema4 from "./vendor/readium.org/webpub-manifest/schema/article.schema.json" with { type: "json" }
import schema5 from "./vendor/readium.org/webpub-manifest/schema/chapter.schema.json" with { type: "json" }
import schema6 from "./vendor/readium.org/webpub-manifest/schema/collection.schema.json" with { type: "json" }
import schema7 from "./vendor/readium.org/webpub-manifest/schema/contributor.schema.json" with { type: "json" }
import schema8 from "./vendor/readium.org/webpub-manifest/schema/episode.schema.json" with { type: "json" }
import schema9 from "./vendor/readium.org/webpub-manifest/schema/extensions/encryption/properties.schema.json" with { type: "json" }
import schema10 from "./vendor/readium.org/webpub-manifest/schema/extensions/epub/metadata.schema.json" with { type: "json" }
import schema11 from "./vendor/readium.org/webpub-manifest/schema/extensions/epub/properties.schema.json" with { type: "json" }
import schema12 from "./vendor/readium.org/webpub-manifest/schema/issue.schema.json" with { type: "json" }
import schema13 from "./vendor/readium.org/webpub-manifest/schema/language-map.schema.json" with { type: "json" }
import schema14 from "./vendor/readium.org/webpub-manifest/schema/link.schema.json" with { type: "json" }
import schema15 from "./vendor/readium.org/webpub-manifest/schema/metadata.schema.json" with { type: "json" }
import schema16 from "./vendor/readium.org/webpub-manifest/schema/periodical.schema.json" with { type: "json" }
import schema17 from "./vendor/readium.org/webpub-manifest/schema/season.schema.json" with { type: "json" }
import schema18 from "./vendor/readium.org/webpub-manifest/schema/series.schema.json" with { type: "json" }
import schema19 from "./vendor/readium.org/webpub-manifest/schema/storyArc.schema.json" with { type: "json" }
import schema20 from "./vendor/readium.org/webpub-manifest/schema/subcollection.schema.json" with { type: "json" }
import schema21 from "./vendor/readium.org/webpub-manifest/schema/subject.schema.json" with { type: "json" }
import schema22 from "./vendor/readium.org/webpub-manifest/schema/volume.schema.json" with { type: "json" }
import schema23 from "./vendor/specs.opds.io/schema/acquisition-object.schema.json" with { type: "json" }
import schema24 from "./vendor/specs.opds.io/schema/feed-metadata.schema.json" with { type: "json" }
import schema25 from "./vendor/specs.opds.io/schema/feed.schema.json" with { type: "json" }
import schema26 from "./vendor/specs.opds.io/schema/properties.schema.json" with { type: "json" }
import schema27 from "./vendor/specs.opds.io/schema/publication.schema.json" with { type: "json" }

export const allSchemas: AnySchemaObject[] = [
  schema0,
  schema1,
  schema2,
  schema3,
  schema4,
  schema5,
  schema6,
  schema7,
  schema8,
  schema9,
  schema10,
  schema11,
  schema12,
  schema13,
  schema14,
  schema15,
  schema16,
  schema17,
  schema18,
  schema19,
  schema20,
  schema21,
  schema22,
  schema23,
  schema24,
  schema25,
  schema26,
  schema27,
]
