// GENERATED by schemas/sync.ts. do not edit.
export const roots = {
  feed: "https://specs.opds.io/schema/feed.schema.json",
  authentication: "https://drafts.opds.io/schema/authentication.schema.json",
  progression: "https://drafts.opds.io/schema/progression.schema.json",
} as const
