/* eslint-disable */
/**
 * GENERATED by schemas/sync.ts from the OPDS/Readium JSON Schemas.
 * DO NOT EDIT BY HAND. run `yarn schemas:sync` to regenerate.
 */

import type { Link } from "./feed.ts"

export interface OPDSAuthenticationDocument {
  /**
   * Title of the Catalog being accessed
   */
  title: string
  /**
   * Unique identifier for the Catalog provider and canonical location for the Authentication Document
   */
  id: string
  /**
   * A description of the service being displayed to the user
   */
  description?: string
  links?: Link[]
  /**
   * A list of supported Authentication Flows
   */
  authentication: {
    type: string
    links?: Link[]
    labels?: {
      login?: string
      password?: string
    }
  }[]
}
