/* eslint-disable */
/**
 * GENERATED by schemas/sync.ts from the OPDS/Readium JSON Schemas.
 * DO NOT EDIT BY HAND. run `yarn schemas:sync` to regenerate.
 */

export interface OPDSProgressionDocument {
  title?: string
  modified: string
  device: {
    id: string
    name: string
  }
  progression: number
  references?: string[]
}
