import { type SentenceRange } from "./getSentenceRanges.ts"

// NOTE: This code was generated by an LLM. It has been reviewed by
// human software engineers, but it should be treated with caution.

/** A "slot" is a sentence that needs to be synthesised. */
type Slot = { chapterId: string; id: number }

/** An anchor is a time+file position bounding a gap. */
type Anchor = { time: number; audiofile: string }

/**
 * Divide N slots evenly across a time span [left.time, right.time].
 *
 * When the left and right anchors are in different audio files the available
 * time is split into two segments:
 *   - left segment : [left.time,  fileDuration(left.audiofile)] in left.audiofile
 *   - right segment: [0,          right.time]                   in right.audiofile
 *
 * Slots are distributed between the two segments in proportion to the
 * available time in each.  If all the time is on one side every slot goes
 * there.
 */
function buildGapRanges(
  slots: Slot[],
  left: Anchor,
  right: Anchor,
  audioFileDurations: Record<string, number>,
): SentenceRange[] {
  const n = slots.length
  if (n === 0) return []

  if (left.audiofile === right.audiofile) {
    const span = right.time - left.time
    return slots.map((slot, i) => ({
      ...slot,
      audiofile: left.audiofile,
      start: left.time + (span * i) / n,
      end: left.time + (span * (i + 1)) / n,
    }))
  }

  const leftDuration = audioFileDurations[left.audiofile] ?? left.time
  const leftAvail = leftDuration - left.time
  const rightAvail = right.time
  const total = leftAvail + rightAvail

  // Number of slots in the left vs right segment, proportional to available time.
  // Guard against division by zero: if there's no available time anywhere,
  // put everything in the left segment (they'll all get 0-length ranges).
  let n1 = total > 0 ? Math.round(n * (leftAvail / total)) : n
  let n2 = n - n1

  // If one side rounds to 0 but the other has some time, keep it at 0.
  // Only clamp to avoid negative counts.
  n1 = Math.max(0, n1)
  n2 = n - n1

  const result: SentenceRange[] = []

  if (n1 > 0) {
    for (let i = 0; i < n1; i++) {
      result.push({
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        ...slots[i]!,
        audiofile: left.audiofile,
        start: left.time + (leftAvail * i) / n1,
        end: left.time + (leftAvail * (i + 1)) / n1,
      })
    }
  }

  if (n2 > 0) {
    for (let i = 0; i < n2; i++) {
      result.push({
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        ...slots[n1 + i]!,
        audiofile: right.audiofile,
        start: (rightAvail * i) / n2,
        end: (rightAvail * (i + 1)) / n2,
      })
    }
  }

  return result
}

/**
 * Given a sequence of sentence ranges from an entire book,
 * ordered by occurrence in audio, interpolates sentence ranges
 * to fill any gaps.
 *
 * A gap may be:
 *   - A non-linearity between two sequential sentence ranges
 *     in the same chapter, e.g. chapter001#0 -> chapter001#3
 *   - A chapter whose sentence ranges start at a number greater
 *     than 0, e.g. chapter001#330 -> chapter002#2
 *   - A chapter whose sentence ranges end at a number lower
 *     than the total number of sentences in that chapter,
 *     e.g. chapter001#325 -> chapter002#0, where
 *     chapterSentenceCounts["chapter001"] === 330
 */
export function interpolateSentenceRanges(
  sentenceRanges: SentenceRange[],
  chapterSentenceCounts: Record<string, number>,
  audioFileDurations: Record<string, number>,
): SentenceRange[] {
  if (sentenceRanges.length === 0) return []

  const result: SentenceRange[] = []

  // Sentences before the very first known sentence in its chapter.
  // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
  const first = sentenceRanges[0]!
  if (first.id > 0) {
    const slots: Slot[] = Array.from({ length: first.id }, (_, i) => ({
      chapterId: first.chapterId,
      id: i,
    }))
    const left: Anchor = { time: 0, audiofile: first.audiofile }
    const right: Anchor = { time: first.start, audiofile: first.audiofile }
    result.push(...buildGapRanges(slots, left, right, audioFileDurations))
  }

  result.push(first)

  for (let idx = 1; idx < sentenceRanges.length; idx++) {
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    const prev = sentenceRanges[idx - 1]!
    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
    const curr = sentenceRanges[idx]!

    const left: Anchor = { time: prev.end, audiofile: prev.audiofile }
    const right: Anchor = { time: curr.start, audiofile: curr.audiofile }

    const gapSlots: Slot[] = []

    if (prev.chapterId === curr.chapterId) {
      for (let id = prev.id + 1; id < curr.id; id++) {
        gapSlots.push({ chapterId: prev.chapterId, id })
      }
    } else {
      // Trailing sentences missing from the end of prev's chapter.
      const prevTotal = chapterSentenceCounts[prev.chapterId] ?? prev.id + 1
      for (let id = prev.id + 1; id < prevTotal; id++) {
        gapSlots.push({ chapterId: prev.chapterId, id })
      }
      // Leading sentences missing from the start of curr's chapter.
      for (let id = 0; id < curr.id; id++) {
        gapSlots.push({ chapterId: curr.chapterId, id })
      }
    }

    if (gapSlots.length > 0) {
      result.push(...buildGapRanges(gapSlots, left, right, audioFileDurations))
    }

    result.push(curr)
  }

  // Sentences missing from the end of the last known sentence's chapter.
  // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
  const last = sentenceRanges[sentenceRanges.length - 1]!
  const lastTotal = chapterSentenceCounts[last.chapterId] ?? last.id + 1

  if (last.id < lastTotal - 1) {
    const slots: Slot[] = Array.from(
      { length: lastTotal - 1 - last.id },
      (_, i) => ({ chapterId: last.chapterId, id: last.id + 1 + i }),
    )
    const fileEnd = audioFileDurations[last.audiofile] ?? last.end
    const left: Anchor = { time: last.end, audiofile: last.audiofile }
    const right: Anchor = { time: fileEnd, audiofile: last.audiofile }
    result.push(...buildGapRanges(slots, left, right, audioFileDurations))
  }

  return result
}
